<a href="https://colab.research.google.com/github/AjMing/-Simple-Sorting/blob/master/Exercise_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Here is BASIC PYTHON commands***

*To print value*

In [ ]:
print(7+5)

12


Data type

In [ ]:
a=5
b=6
print(type(a))  #Check data type
c= float(a+b)
print(type(c) )

<class 'int'>
<class 'float'>


In [ ]:
a=10+20
print(a)
print(type(a))
s="Good morning"
print(type(s))
print(s + " "+str(a));


30
<class 'int'>
<class 'str'>
Good morning 30


Function

In [ ]:
def square(x):
  return x**2 #indent is required

In [ ]:
print(square(4))

16


List

In [ ]:
a=10
b="haha"
c=10.9
ls=[a , b,c]  # , is used to separate each data type
print(ls)
print(type(ls))

[10, 'haha', 10.9]
<class 'list'>


In [ ]:
print(ls[1])
print(ls[-1])


haha
10.9


In [ ]:
print(ls[1:2])
print(ls[:3])
print(ls[1:])


['haha']
[10, 'haha', 10.9]
['haha', 10.9]


LOOP

In [ ]:
for x in range(5):
    print(x)

0
1
2
3
4


In [ ]:
for x in range(2,5):
    print(x)

2
3
4


Import Library

In [ ]:
height=[1.56, 1.79 ,1.89]
sq_height=height**2

TypeError: ignored

In [ ]:

import numpy
np_height=numpy.array(height)
sq_height=np_height**2

In [ ]:
import numpy as np
x=np.array([1, 2 ,-1])
print(x>0)

[ True  True False]


In [ ]:
y=x[x>0]
print(y)

[2]


In [ ]:
arr=numpy.array([[1,2,3],[4,5,6]])
print(arr[0])
print(arr[0,1])
print(arr[1][0])

[1 2 3]
2
4


In [ ]:
print(np.mean(arr))

3.5


In [ ]:
print(np.mean(arr[1]))

5.0


In [ ]:
A=np.array([[1,1],[1,2],[1,3]])
B=np.array([[2,1],[2,2],[2,3]])
C=A@B.T
print(C)

[[ 3  4  5]
 [ 4  6  8]
 [ 5  8 11]]


In [ ]:
np.random.seed(0)
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])